In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [6]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
np.arange(10,25,5)

array([10, 15, 20])

In [10]:
e=np.linspace(0,2,9)

In [11]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [13]:
x=np.eye(2)
y=np.random.random((2,2))
x

array([[1., 0.],
       [0., 1.]])

In [14]:
y

array([[0.25260067, 0.26580838],
       [0.02858878, 0.38403215]])

In [15]:
np.shape(a)


(3,)

In [16]:
np.shape(b)

(2, 3)

In [17]:
np.shape(c)

(2, 2, 3)

In [18]:
np.ndim(a)

1

In [19]:
np.ndim(b)

2

In [20]:
np.ndim(c)

3

In [21]:
np.size(a)

3

In [22]:
np.size(b)

6

In [23]:
np.size(c)

12

In [24]:
a.dtype

dtype('int64')

In [25]:
b.dtype

dtype('float64')

In [26]:
c.dtype

dtype('float64')

In [27]:
a.dtype.name

'int64'

In [28]:
b.dtype.name

'float64'

In [29]:
c.dtype.name

'float64'

In [30]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
x=np.multiply(b,b)

In [32]:
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [33]:

np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [35]:

np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [36]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [37]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [39]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [40]:
np.min(a)

np.int64(1)

In [41]:
np.max(a)

np.int64(3)

In [42]:
np.cumsum(a)

array([1, 3, 6])

In [43]:
np.mean(a)

np.float64(2.0)

In [44]:
np.median(a)

np.float64(2.0)

In [45]:

np.std(a)

np.float64(0.816496580927726)